server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.30:8761/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostName: 192.168.3.30      

spring:
  cloud:    
    inetutils:
      default-hostname: 192.168.3.30
      timeout-seconds: 5

eureka:
  instance:
    ip-address: 192.168.3.30
    prefer-ip-address: true
    preferIpAddress: true
