server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.30:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

spring:
  cloud:    
    inetutils:
      default-hostname: 192.168.3.30
      timeout-seconds: 5
